// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/blog/v1/rpc/user-rpc/internal/logic"
	"github.com/blog/v1/rpc/user-rpc/internal/svc"
	user "github.com/blog/v1/rpc/user-rpc/user"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) Login(ctx context.Context, in *user.ReqLogin) (*user.BaseUser, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UsersServer) Create(ctx context.Context, in *user.UserParams) (*user.BaseUser, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *UsersServer) Destroy(ctx context.Context, in *user.UserId) (*user.CommonOK, error) {
	l := logic.NewDestroyLogic(ctx, s.svcCtx)
	return l.Destroy(in)
}
