// Code generated by goctl. DO NOT EDIT.
package types

type UserId struct {
	Id int64 `path:"id"`
}

type UserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Phone    string `json:"phone"`
	Name     string `json:"name"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type BaseUser struct {
	UserId
	Username  string `json:"username"`
	Avatar    string `json:"avatar"`
	Phone     string `json:"phone"`
	Name      string `json:"name"`
	Address   string `json:"address"`
	Birthday  string `json:"birthday"`
	CreatedAt string `json:"createdAt"`
}

type ReqLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RespLogin struct {
	Token string `json:"token"`
}

type CommonOK struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
