// Code generated by goctl. DO NOT EDIT.
package types

type ReqId struct {
	Id int64 `json:"id"`
}

type ReqCreate struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Phone    string `json:"phone"`
	Name     string `json:"name"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type RespUser struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Avatar    string `json:"avatar"`
	Phone     string `json:"phone"`
	Name      string `json:"name"`
	Address   string `json:"address"`
	Birthday  string `json:"birthday"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ReqLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type ReqUpdate struct {
	Id       int64  `path:"id"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Phone    string `json:"phone"`
	Name     string `json:"name"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type RespLogin struct {
	Token string `json:"token"`
}

type RespComm struct {
	Ok    bool   `json:"ok"`
	Error string `json:"error"`
}
